### ISSUE TITLE
Unmentioned dependencies

### ISSUE THREAD

**Issue by rwilhelm** [phischu/fragnix#113]
To successfully get this running I needed to `cabal install tasty-golden happy cpphs`. I'm not sure how you'd handle this, but maybe it should be mentioned in the readme.

**Comment by phischu** [comment]
This is a known [issue in cabal](https://github.com/haskell/cabal/issues/220). It is possible that [stack](https://github.com/commercialhaskell/stack) makes the installation experience more pleasant. Sadly the  [travis file](https://github.com/phischu/fragnix/blob/master/.travis.yml) also has to explictly install `cpphs` and `happy`. I will mention it in the readme.
