### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by phischu** [phischu/fragnix#128]
We want to add different commands like `init`, `publish`, `fetch`. The current behavior would be under `build`. Those commands will talk to a (hard-coded) server. We better implement this server first.

**Comment by phischu** [comment]
In light of updates, we need `fragnix build src/Main.hs`, `fragnix diff env1 env2 my-cool-update`, and `fragnix update my-cool-update`.

**Comment by phischu** [comment]
Or, we could have multiple executables `fragnix-build`, `fragnix-diff`, `fragnix-update`.

**Comment by BinderDavid** [comment]
Sub-commands are very simple to implement with optparse-applicative, so let's go that way.

**Comment by phischu** [comment]
This is done.
