### ISSUE TITLE
Rearrange folder layout to make environment user-visible

### ISSUE THREAD

**Issue by phischu** [phischu/fragnix#141]
Currently all fragnix-specific files and folders are in a folder `fragnix`. We want the following layout:

```
src/Main.hs
src/...
env/Data.Map.Map
env/...
.fragnix/slices/...
.fragnix/...
```

**Comment by BinderDavid** [comment]
I'll do this.

**Comment by BinderDavid** [comment]
I propose the following structure of the file directory, and the semantic of the various fragnix commands:

**Comment by phischu** [comment]
I strongly agree that there are two different workflows for application developers and for library developers and currently we muddle both together. Some terminology: "environment" denotes the entire content of `env`, not a single file that corresponds to a module like `Data.Map`. I agree with the proposed folder layout except for one big thing: the indirection in `env` pointing to hidden files through hashes. Firstly, I don't see how it is necessary for any of the currently planned features. Perhaps it is, but we can still do it later. Secondly, it would mean we start dealing in more coarse-grained units than slices. If we had updates of type `[(EnvironmentHash, EnvironmentHash)]`, like you propose, we would update entire modules, not individual slices.

I propose to first implement the following layout for now:

Hidden fragnix folder:
```
.fragnix/
  slices/
    2/4/
      2499345
    5/3/
      5323124
  compilationunits/
    2/4/
       F2499345.hs
       F2499345.hs-boot
    5/3/
      F5323124.hs
      F5323124.hs-boot
  build/
        F5323124.o
        F5323124.hi
        F2499345.o
        F2499345.hi
  updates/
    containers-v.2.0-to-containers-v.3.0
```

User visible environment:

```
src/
  Main.hs
env/
  Data.Map
  GHC.Prim
  Main
```
