### ISSUE TITLE
Why not submodules?

### ISSUE THREAD

**Issue by joehillen** [phischu/fragnix#97]
From installation instructions:
```
git clone -b fragnix https://github.com/phischu/haskell-names
git clone -b fragnix https://github.com/phischu/haskell-src-exts
```

Why aren't you using git submodules for this?

**Comment by phischu** [comment]
Thanks, for the suggestion, I didn't know about them. Closed with 88488e880eec695fc36d6bb9edebd5a73a55bc2f
